"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
try:
    from decouple import config
except ImportError:
    import os
    config = os.environ.get
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s&)pfotqqt_=1&eoi*a_8g!(h(s^popf2uj*)q*0$l@g34p17$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['ilusion.one', 'www.ilusion.one', '20.69.236.103', 'localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['https://ilusion.one', 'https://www.ilusion.one', 'http://20.69.236.103', 'http://localhost', 'http://127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'application.wsgi.application'

COGNODB_URI = config("COGNODB_URI")
COGNODB_USER = config("COGNODB_USER")
COGNODB_PASSWORD = config("COGNODB_PASSWORD")


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

CLOUDFLARE_ACCOUNT_ID= config("R2_ACCOUNT_ID")
CLOUDFLARE_BUCKET_NAME = config("R2_BUCKET_NAME")
CLOUDFLARE_ENDPOINT_URL = config("R2_ENDPOINT")
CLOUDFLARE_ACCESS_KEY_ID= config("R2_ACCESS_KEY_ID")
CLOUDFLARE_SECRET_ACCESS_KEY = config("R2_SECRET_ACCESS_KEY")
CLOUDFLARE_USE_PATH_STYLE_ENDPOINT = config("R2_USE_PATH_STYLE_ENDPOINT")


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    # 'files_storage': {
    #     "ENGINE": "storages.backends.s3boto3.S3Boto3Storage",
    #     "CLIENT_KWARGS": CLOUDFLARE_R2_CONFIG_OPTIONS,
    #     "LOCATION": "files",  # or a subdirectory like "media"
    # }
}


STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "files_storage": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "endpoint_url": (
                f"https://{CLOUDFLARE_ACCOUNT_ID}"
                ".r2.cloudflarestorage.com"
            ),
            "access_key": CLOUDFLARE_ACCESS_KEY_ID,
            "secret_key": CLOUDFLARE_SECRET_ACCESS_KEY,
            "bucket_name": CLOUDFLARE_BUCKET_NAME,
            "region_name": "auto",
            "location": "files",
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "vault:vault_home"
LOGOUT_REDIRECT_URL = "login"

# Upload Limits (200 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
